<?php

namespace backend\controllers;


use common\models\Post;
use yii\web\Controller;

class ApiController extends Controller
{

    public function beforeAction($action)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $this->enableCsrfValidation = false;


        if (\Yii::$app->request->method == 'OPTIONS') {
            return ['method' => 'options'];
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    public function actionPost()
    {
        $perPage = (int)\Yii::$app->request->get('per_page', 50);
        $offset = (int)\Yii::$app->request->get('offset', 0);
        $page = (int)\Yii::$app->request->get('page', 0);

        $posts = Post::find()
            ->with('images')
            ->offset($page * $perPage)
            ->limit($perPage)
            ->all();

        foreach ($posts as $post) {
            foreach ($post->images as $image) {
                if ($image->active == 1) {
                    $post->url = $image->url;
                }
            }
        }

        return [
            'posts' => $posts
        ];
    }

}